src/Entity/Pokemon.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\PokemonRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ApiResource()
 * @ORM\Entity(repositoryClass=PokemonRepository::class)
 */
class Pokemon
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type_1;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type_2;

    /**
     * @ORM\Column(type="integer")
     */
    private $total;

    /**
     * @ORM\Column(type="integer")
     */
    private $hp;

    /**
     * @ORM\Column(type="integer")
     */
    private $attack;

    /**
     * @ORM\Column(type="integer")
     */
    private $defense;

    /**
     * @ORM\Column(type="integer")
     */
    private $sp_atk;

    /**
     * @ORM\Column(type="integer")
     */
    private $sp_def;

    /**
     * @ORM\Column(type="integer")
     */
    private $speed;

    /**
     * @ORM\Column(type="integer")
     */
    private $generation;

    /**
     * @ORM\Column(type="boolean")
     */
    private $legendary;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getType1(): ?string
    {
        return $this->type_1;
    }

    public function setType1(string $type_1): self
    {
        $this->type_1 = $type_1;

        return $this;
    }

    public function getType2(): ?string
    {
        return $this->type_2;
    }

    public function setType2(string $type_2): self
    {
        $this->type_2 = $type_2;

        return $this;
    }

    public function getTotal(): ?int
    {
        return $this->total;
    }

    public function setTotal(int $total): self
    {
        $this->total = $total;

        return $this;
    }

    public function getHp(): ?int
    {
        return $this->hp;
    }

    public function setHp(int $hp): self
    {
        $this->hp = $hp;

        return $this;
    }

    public function getAttack(): ?int
    {
        return $this->attack;
    }

    public function setAttack(int $attack): self
    {
        $this->attack = $attack;

        return $this;
    }

    public function getDefense(): ?int
    {
        return $this->defense;
    }

    public function setDefense(int $defense): self
    {
        $this->defense = $defense;

        return $this;
    }

    public function getSpAtk(): ?int
    {
        return $this->sp_atk;
    }

    public function setSpAtk(int $sp_atk): self
    {
        $this->sp_atk = $sp_atk;

        return $this;
    }

    public function getSpDef(): ?int
    {
        return $this->sp_def;
    }

    public function setSpDef(int $sp_def): self
    {
        $this->sp_def = $sp_def;

        return $this;
    }

    public function getSpeed(): ?int
    {
        return $this->speed;
    }

    public function setSpeed(int $speed): self
    {
        $this->speed = $speed;

        return $this;
    }

    public function getGeneration(): ?int
    {
        return $this->generation;
    }

    public function setGeneration(int $generation): self
    {
        $this->generation = $generation;

        return $this;
    }

    public function isLegendary(): ?bool
    {
        return $this->legendary;
    }

    public function setLegendary(bool $legendary): self
    {
        $this->legendary = $legendary;

        return $this;
    }
}

src/Form/PokemonType.php
<?php

namespace App\Form;

use App\Entity\Pokemon;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PokemonType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('type_1')
            ->add('type_2')
            ->add('total')
            ->add('hp')
            ->add('attack')
            ->add('defense')
            ->add('sp_atk')
            ->add('sp_def')
            ->add('speed')
            ->add('generation')
            ->add('legendary')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Pokemon::class,
        ]);
    }
}

src/Controller/PokemonController.php
<?php

namespace App\Controller;

use App\Entity\Pokemon;
use App\Form\PokemonType;
use App\Repository\PokemonRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/pokemon")
 */
class PokemonController extends AbstractController
{
    /**
     * @Route("/", name="app_pokemon_index", methods={"GET"})
     */
    public function index(PokemonRepository $pokemonRepository): Response
    {
        return $this->render('pokemon/index.html.twig', [
            'pokemon' => $pokemonRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_pokemon_new", methods={"GET", "POST"})
     */
    public function new(Request $request, PokemonRepository $pokemonRepository): Response
    {
        $pokemon = new Pokemon();
        $form = $this->createForm(PokemonType::class, $pokemon);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $pokemonRepository->add($pokemon, true);

            return $this->redirectToRoute('app_pokemon_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('pokemon/new.html.twig', [
            'pokemon' => $pokemon,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_pokemon_show", methods={"GET"})
     */
    public function show(Pokemon $pokemon): Response
    {
        return $this->render('pokemon/show.html.twig', [
            'pokemon' => $pokemon,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_pokemon_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Pokemon $pokemon, PokemonRepository $pokemonRepository): Response
    {
        $form = $this->createForm(PokemonType::class, $pokemon);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $pokemonRepository->add($pokemon, true);

            return $this->redirectToRoute('app_pokemon_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('pokemon/edit.html.twig', [
            'pokemon' => $pokemon,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_pokemon_delete", methods={"POST"})
     */
    public function delete(Request $request, Pokemon $pokemon, PokemonRepository $pokemonRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$pokemon->getId(), $request->request->get('_token'))) {
            $pokemonRepository->remove($pokemon, true);
        }

        return $this->redirectToRoute('app_pokemon_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

templates/pokemon/_delete_form.html.twig
<form method="post" action="{{ path('app_pokemon_delete', {'id': pokemon.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ pokemon.id) }}">
    <button class="btn">Delete</button>
</form>

templates/pokemon/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/pokemon/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Pokemon{% endblock %}

{% block body %}
    <h1>Edit Pokemon</h1>

    {{ include('pokemon/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_pokemon_index') }}">back to list</a>

    {{ include('pokemon/_delete_form.html.twig') }}
{% endblock %}

templates/pokemon/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Pokemon index{% endblock %}

{% block body %}
    <h1>Pokemon index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Type_1</th>
                <th>Type_2</th>
                <th>Total</th>
                <th>Hp</th>
                <th>Attack</th>
                <th>Defense</th>
                <th>Sp_atk</th>
                <th>Sp_def</th>
                <th>Speed</th>
                <th>Generation</th>
                <th>Legendary</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for pokemon in pokemon %}
            <tr>
                <td>{{ pokemon.id }}</td>
                <td>{{ pokemon.name }}</td>
                <td>{{ pokemon.type1 }}</td>
                <td>{{ pokemon.type2 }}</td>
                <td>{{ pokemon.total }}</td>
                <td>{{ pokemon.hp }}</td>
                <td>{{ pokemon.attack }}</td>
                <td>{{ pokemon.defense }}</td>
                <td>{{ pokemon.spAtk }}</td>
                <td>{{ pokemon.spDef }}</td>
                <td>{{ pokemon.speed }}</td>
                <td>{{ pokemon.generation }}</td>
                <td>{{ pokemon.legendary ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('app_pokemon_show', {'id': pokemon.id}) }}">show</a>
                    <a href="{{ path('app_pokemon_edit', {'id': pokemon.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="14">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_pokemon_new') }}">Create new</a>
{% endblock %}

templates/pokemon/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Pokemon{% endblock %}

{% block body %}
    <h1>Create new Pokemon</h1>

    {{ include('pokemon/_form.html.twig') }}

    <a href="{{ path('app_pokemon_index') }}">back to list</a>
{% endblock %}

templates/pokemon/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Pokemon{% endblock %}

{% block body %}
    <h1>Pokemon</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ pokemon.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ pokemon.name }}</td>
            </tr>
            <tr>
                <th>Type_1</th>
                <td>{{ pokemon.type1 }}</td>
            </tr>
            <tr>
                <th>Type_2</th>
                <td>{{ pokemon.type2 }}</td>
            </tr>
            <tr>
                <th>Total</th>
                <td>{{ pokemon.total }}</td>
            </tr>
            <tr>
                <th>Hp</th>
                <td>{{ pokemon.hp }}</td>
            </tr>
            <tr>
                <th>Attack</th>
                <td>{{ pokemon.attack }}</td>
            </tr>
            <tr>
                <th>Defense</th>
                <td>{{ pokemon.defense }}</td>
            </tr>
            <tr>
                <th>Sp_atk</th>
                <td>{{ pokemon.spAtk }}</td>
            </tr>
            <tr>
                <th>Sp_def</th>
                <td>{{ pokemon.spDef }}</td>
            </tr>
            <tr>
                <th>Speed</th>
                <td>{{ pokemon.speed }}</td>
            </tr>
            <tr>
                <th>Generation</th>
                <td>{{ pokemon.generation }}</td>
            </tr>
            <tr>
                <th>Legendary</th>
                <td>{{ pokemon.legendary ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_pokemon_index') }}">back to list</a>

    <a href="{{ path('app_pokemon_edit', {'id': pokemon.id}) }}">edit</a>

    {{ include('pokemon/_delete_form.html.twig') }}
{% endblock %}